version: "3.6"

services:
  ghost:
    image: ghost:5-alpine
    ports:
      - "2368:2368"
    volumes:
      - "ghost_data:/var/lib/ghost/content"
    environment:
      NODE_ENV: development
      url: http://localhost:2368

volumes:
  ghost_data:
