version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - restore_cache:
          key: deps-v2-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install

      - save_cache:
          key: deps-v2-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test

  build-docker-image:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build docker image
          command: |
            export D_RELEASE=0.2.2
            wget -O - https://cdn.rawgit.com/f213/d/351d2459/install.sh|sh
            ./d build-image f213/website .
            ./d push-image f213/website


  deploy:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: Install deploy tooling
          command: |
            export D_RELEASE=0.2.5
            wget -O - https://cdn.rawgit.com/f213/d/351d2459/install.sh|sh
      - run:
          name: Update image
          command: |
            ./d add-host-key --force
            ./d update-image circle@borshev.com blog  f213/website:${CIRCLE_SHA1}

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build
      - build-docker-image:
          requires:
            - build
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build-docker-image
