version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: cimg/node:16.7.0

    steps:
      - checkout
      - restore_cache:
          key: deps-v3-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install

      - save_cache:
          key: deps-v3-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test

  deploy:
    docker:
      - image: cimg/python:3.9.6

    steps:
      - checkout
      - run:
          name: Install deploy tooling
          command: |
            export D_RELEASE=0.5.1
            wget -O - https://raw.githubusercontent.com/f213/d/master/install.sh|sh
      - run:
          name: Update image
          command: |
            ./d add-host-key --force
            ./d update-image circle@92.53.67.149 blog  f213/website:${CIRCLE_SHA1}

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build
      - docker/publish:
          requires:
            - build
          filters:
            branches:
              only: master
          image: f213/website
          cache_from: f213/website
          tag: 'latest,${CIRCLE_SHA1}'
          extra_build_args: "--build-arg RELEASE=${CIRCLE_SHA1}"

      - deploy:
          requires:
            - docker/publish
