version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          key: deps-v2-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install

      - save_cache:
          key: deps-v2-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test

      - setup_remote_docker

      - run:
          name: Build docker image
          command: |
            export D_RELEASE=0.2.2
            wget -O - https://cdn.rawgit.com/f213/d/351d2459/install.sh|sh
            ./d build-image f213/website .

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build

