name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci --no-audit

      - name: Run the linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build
